'use strict';

module.exports = {
    rules: {
        'await-promise': true,
        'ban': false,
        'curly': [true, 'ignore-same-line'],
        'forin': true,
        'import-blacklist': true,
        'label-position': true,
        'no-arg': true,
        'no-bitwise': true,
        'no-conditional-assignment': true,
        'no-console': [true, 'error', 'log'],
        'no-construct': true,
        'no-debugger': true,
        'no-duplicate-super': true,
        'no-duplicate-variable': true,
        'no-empty': true,
        'no-eval': true,
        'no-floating-promises': true,
        'no-for-in-array': true,
        'no-inferred-empty-object-type': true,
        'no-invalid-template-strings': true,
        'no-invalid-this': true,
        'no-misused-new': true,
        'no-null-keyword': false,
        'no-shadowed-variable': true,
        'no-sparse-arrays': true,
        'no-string-literal': true,
        'no-string-throw': true,
        'no-switch-case-fall-through': true,
        'no-unbound-method': true,
        'no-unsafe-any': false,
        'no-unsafe-finally': true,
        'no-unused-expression': [true, 'allow-fast-null-checks'],
        'no-unused-variable': true,
        'no-use-before-declare': true,
        'no-var-keyword': true,
        'no-void-expression': false,
        'radix': true,
        'restrict-plus-operands': true,
        'strict-boolean-expressions': false,
        'strict-type-predicates': true,
        'switch-default': true,
        'triple-equals': true,
        'typeof-compare': true,
        'use-isnan': true
    }
};
